import type { Masseuse, ServiceCategory } from "./types";

/**
 * Mirrors LAmour.Api/Data/SeedData.cs so the UI is fully explorable in local dev
 * even before the .NET backend is running. Real data always wins once
 * NEXT_PUBLIC_API_URL responds — see lib/api.ts.
 */
export const MOCK_CATEGORIES: ServiceCategory[] = [
  {
    id: 1,
    name: "Masajes Eróticos & Tántricos",
    slug: "eroticos-tantricos",
    description: "Rituales sensoriales diseñados para liberar tensión y despertar los sentidos.",
    highlight: "Todos los masajes eróticos incluyen estimulación al finalizar la terapia.",
    displayOrder: 1,
    isActive: true,
    services: [
      {
        id: 1,
        serviceCategoryId: 1,
        name: "Ritual L'AMOUR (Full Nuru)",
        slug: "ritual-lamour-full-nuru",
        shortDescription: "Nuestro ritual insignia: cuerpo a cuerpo con aceite Nuru premium de principio a fin.",
        longDescription: "Nuestro ritual insignia y el más solicitado: cuerpo a cuerpo completo con aceite Nuru premium, deslizante y cálido, de principio a fin de los 90 minutos. Incluye estimulación al finalizar y se adapta al ritmo que tú marques, sin prisa y sin pasos que te saltes.",
        durationMinutes: 90,
        price: 320000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Aceite Nuru premium", "Cuerpo a cuerpo integral", "Estimulación incluida al finalizar"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 2,
        serviceCategoryId: 1,
        name: "Salvaje (Cambio de Roles)",
        slug: "salvaje-cambio-de-roles",
        shortDescription: "Ella toma el control: una experiencia intensa donde los roles se invierten.",
        longDescription: "Ella toma el control desde el primer minuto: un ritual donde los roles tradicionales se invierten y la iniciativa queda en sus manos. Ideal para quien busca soltar el control y dejarse llevar por completo, con estimulación incluida al cierre de los 75 minutos.",
        durationMinutes: 75,
        price: 280000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Ella toma el control", "Juego de roles", "Estimulación incluida al finalizar"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 3,
        serviceCategoryId: 1,
        name: "Masaje a Cuatro Manos",
        slug: "masaje-cuatro-manos",
        shortDescription: "Dos masajistas, un solo ritmo: una sensación envolvente e inolvidable.",
        longDescription: "Dos terapeutas certificadas trabajan en perfecta sincronía sobre tu cuerpo, multiplicando cada sensación en una coreografía de movimientos simultáneos. 90 minutos pensados para quienes ya conocen nuestros rituales y quieren llevar la experiencia a otro nivel, con estimulación incluida al finalizar.",
        durationMinutes: 90,
        price: 420000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["2 masajistas en sincronía", "Sensación envolvente", "Estimulación incluida al finalizar"],
        requiresTwoTherapists: true,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  {
    id: 2,
    name: "Terapias Especiales",
    slug: "terapias-especiales",
    description: "Rituales con elementos térmicos y técnicas de contacto que profundizan la relajación.",
    highlight: null,
    displayOrder: 2,
    isActive: true,
    services: [
      {
        id: 4,
        serviceCategoryId: 2,
        name: "Piedras Volcánicas",
        slug: "piedras-volcanicas",
        shortDescription: "Calor profundo con piedras volcánicas para liberar la tensión muscular.",
        longDescription: "Piedras volcánicas calientes se deslizan y reposan sobre los puntos de mayor tensión, combinando calor profundo con técnica manual para liberar contracturas que el masaje convencional no siempre alcanza. 75 minutos en un ambiente cálido y envolvente, ideal para el estrés acumulado en cuello, espalda y hombros.",
        durationMinutes: 75,
        price: 240000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Terapia de calor", "Libera tensión profunda", "Ambiente relajante"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 5,
        serviceCategoryId: 2,
        name: "Terapia con Aceites Calientes",
        slug: "aceites-calientes",
        shortDescription: "Aceites tibios deslizándose en movimientos largos y envolventes.",
        longDescription: "Aceites esenciales tibios se deslizan en movimientos largos y continuos por todo el cuerpo, combinando el efecto relajante del calor con una técnica envolvente de cuerpo completo. 60 minutos pensados para desconectar por completo, sin prisa.",
        durationMinutes: 60,
        price: 210000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Aceites esencia tibios", "Movimientos envolventes"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 6,
        serviceCategoryId: 2,
        name: "Ritual de Contacto Total",
        slug: "ritual-contacto-total",
        shortDescription: "Un recorrido completo de contacto consciente por todo el cuerpo.",
        longDescription: "Un recorrido completo de contacto consciente por todo el cuerpo, acompañado de una técnica de respiración guiada que ayuda a soltar la tensión mental además de la física. 90 minutos de presencia total, ideal para quienes buscan una experiencia profunda más allá del masaje tradicional.",
        durationMinutes: 90,
        price: 300000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Contacto integral", "Técnica de respiración guiada"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 3,
        isActive: true,
      },
      {
        id: 7,
        serviceCategoryId: 2,
        name: "Experiencia Piel con Piel",
        slug: "piel-con-piel",
        shortDescription: "Cercanía y calidez en su forma más pura.",
        longDescription: "Cercanía y calidez en su forma más pura: una sesión de contacto directo, sin barreras, enfocada en la conexión más que en la técnica. 60 minutos para quienes buscan sentir presencia real, sin distancia.",
        durationMinutes: 60,
        price: 230000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Contacto directo", "Máxima cercanía"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 4,
        isActive: true,
      },
      {
        id: 8,
        serviceCategoryId: 2,
        name: "Cuerpo a Cuerpo",
        slug: "cuerpo-a-cuerpo",
        shortDescription: "Técnica clásica de deslizamiento corporal para una relajación absoluta.",
        longDescription: "Técnica clásica de deslizamiento corporal completo, donde el propio cuerpo de la terapeuta se convierte en la herramienta de masaje. 75 minutos de relajación absoluta, combinando presión controlada y movimientos fluidos de principio a fin.",
        durationMinutes: 75,
        price: 260000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Deslizamiento corporal", "Relajación absoluta"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 5,
        isActive: true,
      },
    ],
  },
  {
    id: 3,
    name: "Masajes Sensoriales",
    slug: "sensoriales",
    description: "Sesiones de 60 minutos enfocadas en el placer de los sentidos, con tiempo adicional opcional.",
    highlight: null,
    displayOrder: 3,
    isActive: true,
    services: [
      {
        id: 9,
        serviceCategoryId: 3,
        name: "Masaje Sensorial",
        slug: "masaje-sensorial",
        shortDescription: "60 minutos de estimulación de los sentidos, con opción de vestidura sensorial.",
        longDescription: "60 minutos enfocados en despertar cada sentido, con movimientos pausados y una atención especial a las zonas de mayor sensibilidad. Puedes sumar tiempo adicional o elegir la modalidad con vestidura sensorial (en panty) si prefieres una experiencia más sutil.",
        durationMinutes: 60,
        price: 200000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Opción con vestidura sensorial (en panty)", "Tiempo adicional disponible"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: true,
        allowsExtraTime: true,
        isCoupleExperience: false,
        displayOrder: 1,
        isActive: true,
      },
    ],
  },
  {
    id: 4,
    name: "Experiencias en Pareja",
    slug: "experiencias-pareja",
    description: "Momentos diseñados para compartir, conectar y explorar en compañía.",
    highlight: null,
    displayOrder: 4,
    isActive: true,
    services: [
      {
        id: 10,
        serviceCategoryId: 4,
        name: "Experiencia en Pareja",
        slug: "experiencia-en-pareja",
        shortDescription: "Un masajista dedicado para cada persona, en la misma habitación.",
        longDescription: "Cada integrante de la pareja tiene su propio terapeuta certificado, y ambos viven la sesión al mismo tiempo, en la misma habitación, sincronizados en cada movimiento. 60 minutos pensados para compartir un momento de relajación juntos, sin que ninguno tenga que esperar su turno.",
        durationMinutes: 60,
        price: 480000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Un masajista por persona", "Misma habitación", "Sincronía total"],
        requiresTwoTherapists: true,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: true,
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 11,
        serviceCategoryId: 4,
        name: "Masaje Interactivo",
        slug: "masaje-interactivo",
        shortDescription: "El terapeuta guía a la pareja para que se masajeen mutuamente.",
        longDescription: "El terapeuta guía a la pareja paso a paso para que se masajeen mutuamente, enseñando técnicas de contacto consciente que pueden repetir después, en casa. 60 minutos tan didácticos como íntimos, ideales para fortalecer la conexión física entre los dos.",
        durationMinutes: 60,
        price: 350000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Guiado por un terapeuta", "Conexión activa en pareja"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: true,
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 12,
        serviceCategoryId: 4,
        name: "Masaje Voyerista",
        slug: "masaje-voyerista",
        shortDescription: "El Arte de Mirar: conexión a través de los sentidos.",
        longDescription: "El Arte de Mirar: uno de los dos se entrega por completo a la relajación mientras el otro observa cada movimiento de cerca, alimentando la fantasía y la complicidad de la pareja. 60 minutos que despiertan tanto a quien recibe como a quien mira.",
        durationMinutes: 60,
        price: 260000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Uno se relaja, el otro observa", "Alimenta la complicidad"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: true,
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  {
    id: 5,
    name: "Relajación y Muscular",
    slug: "relajacion-muscular",
    description: "Terapias clásicas enfocadas en el bienestar físico y la recuperación muscular.",
    highlight: null,
    displayOrder: 5,
    isActive: true,
    services: [
      {
        id: 13,
        serviceCategoryId: 5,
        name: "Masaje de Relajación Clásico",
        slug: "relajacion-clasica",
        shortDescription: "Técnica sueca clásica para liberar el estrés del día a día.",
        longDescription: "Técnica sueca clásica, con presión media y movimientos largos y envolventes, diseñada para liberar el estrés acumulado del día a día. 60 minutos ideales si es tu primera experiencia con nosotros o buscas una sesión más tradicional.",
        durationMinutes: 60,
        price: 150000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Técnica sueca", "Libera estrés"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 14,
        serviceCategoryId: 5,
        name: "Exfoliación Corporal",
        slug: "exfoliacion-corporal",
        shortDescription: "Renueva tu piel con una exfoliación completa de cuerpo.",
        longDescription: "Una exfoliación completa de cuerpo con sales y aceites naturales que elimina células muertas y deja la piel visiblemente más suave. 45 minutos que puedes combinar con cualquier otro ritual para preparar la piel antes del masaje.",
        durationMinutes: 45,
        price: 130000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Piel renovada", "Sales y aceites naturales"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 15,
        serviceCategoryId: 5,
        name: "Masaje en Pies (Reflexología)",
        slug: "masaje-pies-reflexologia",
        shortDescription: "Puntos de reflexología para aliviar la fatiga y activar la circulación.",
        longDescription: "Trabajo específico sobre los puntos de reflexología del pie, pensado para aliviar la fatiga acumulada y activar la circulación después de un día largo. 30 minutos ideales como complemento de otro servicio o como sesión exprés independiente.",
        durationMinutes: 30,
        price: 90000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Reflexología", "Activa la circulación"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 3,
        isActive: true,
      },
      {
        id: 16,
        serviceCategoryId: 5,
        name: "Recuperación Muscular Profunda",
        slug: "recuperacion-muscular-profunda",
        shortDescription: "Técnica de tejido profundo para deportistas y tensión crónica.",
        longDescription: "Técnica de tejido profundo con presión sostenida sobre los grupos musculares más exigidos, pensada para deportistas y para tensión crónica que no cede con un masaje suave. 75 minutos enfocados en el resultado, no solo en la relajación.",
        durationMinutes: 75,
        price: 220000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Tejido profundo", "Ideal post-entrenamiento"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 4,
        isActive: true,
      },
    ],
  },
];

export const MOCK_MASSEUSES: Masseuse[] = [
  { id: 1, stageName: "Valentina", age: 28, bio: "Especialista en rituales tántricos y terapias de contacto total, con más de 5 años de experiencia.", photoUrl: null, photoGallery: [], displayOrder: 1, isActive: true },
  { id: 2, stageName: "Isabella", age: 25, bio: "Experta en masajes sensoriales y experiencias en pareja, enfocada en la conexión y la calidez.", photoUrl: null, photoGallery: [], displayOrder: 2, isActive: true },
  { id: 3, stageName: "Camila", age: 31, bio: "Terapeuta certificada en recuperación muscular y piedras volcánicas.", photoUrl: null, photoGallery: [], displayOrder: 3, isActive: true },
  { id: 4, stageName: "Sofía", age: 27, bio: "Especialista en masajes a cuatro manos y rituales L'AMOUR.", photoUrl: null, photoGallery: [], displayOrder: 4, isActive: true },
];
