import type { Masseuse, ServiceCategory } from "./types";

/**
 * Mirrors LAmour.Api/Data/SeedData.cs so the UI is fully explorable in local dev
 * even before the .NET backend is running. Real data always wins once
 * NEXT_PUBLIC_API_URL responds — see lib/api.ts.
 */
export const MOCK_CATEGORIES: ServiceCategory[] = [
  {
    id: 1,
    name: "Masajes Eróticos & Tántricos",
    slug: "eroticos-tantricos",
    description: "Rituales sensoriales diseñados para liberar tensión y despertar los sentidos.",
    highlight: "Todos los masajes eróticos incluyen estimulación al finalizar la terapia.",
    displayOrder: 1,
    isActive: true,
    services: [
      {
        id: 1,
        serviceCategoryId: 1,
        name: "Ritual L'AMOUR (Full Nuru)",
        slug: "ritual-lamour-full-nuru",
        shortDescription: "Nuestro ritual insignia: cuerpo a cuerpo con aceite Nuru premium de principio a fin.",
        longDescription: "Una experiencia envolvente de contacto total con aceite Nuru, diseñada para disolver la tensión y elevar la sensualidad en cada movimiento.",
        durationMinutes: 90,
        price: 320000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Aceite Nuru premium", "Cuerpo a cuerpo integral", "Estimulación incluida al finalizar"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 2,
        serviceCategoryId: 1,
        name: "Salvaje (Cambio de Roles)",
        slug: "salvaje-cambio-de-roles",
        shortDescription: "Ella toma el control: una experiencia intensa donde los roles se invierten.",
        longDescription: "Un ritual atrevido donde la iniciativa cambia de manos, elevando la complicidad y la intensidad de la sesión.",
        durationMinutes: 75,
        price: 280000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Ella toma el control", "Juego de roles", "Estimulación incluida al finalizar"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 3,
        serviceCategoryId: 1,
        name: "Masaje a Cuatro Manos",
        slug: "masaje-cuatro-manos",
        shortDescription: "Dos masajistas, un solo ritmo: una sensación envolvente e inolvidable.",
        longDescription: "Dos terapeutas trabajan en perfecta sincronía para multiplicar cada sensación en una experiencia única.",
        durationMinutes: 90,
        price: 420000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["2 masajistas en sincronía", "Sensación envolvente", "Estimulación incluida al finalizar"],
        requiresTwoTherapists: true,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  {
    id: 2,
    name: "Terapias Especiales",
    slug: "terapias-especiales",
    description: "Rituales con elementos térmicos y técnicas de contacto que profundizan la relajación.",
    highlight: null,
    displayOrder: 2,
    isActive: true,
    services: [
      {
        id: 4,
        serviceCategoryId: 2,
        name: "Piedras Volcánicas",
        slug: "piedras-volcanicas",
        shortDescription: "Calor profundo con piedras volcánicas para liberar la tensión muscular.",
        longDescription: null,
        durationMinutes: 75,
        price: 240000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Terapia de calor", "Libera tensión profunda", "Ambiente relajante"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 5,
        serviceCategoryId: 2,
        name: "Terapia con Aceites Calientes",
        slug: "aceites-calientes",
        shortDescription: "Aceites tibios deslizándose en movimientos largos y envolventes.",
        longDescription: null,
        durationMinutes: 60,
        price: 210000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Aceites esencia tibios", "Movimientos envolventes"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 6,
        serviceCategoryId: 2,
        name: "Ritual de Contacto Total",
        slug: "ritual-contacto-total",
        shortDescription: "Un recorrido completo de contacto consciente por todo el cuerpo.",
        longDescription: null,
        durationMinutes: 90,
        price: 300000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Contacto integral", "Técnica de respiración guiada"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 3,
        isActive: true,
      },
      {
        id: 7,
        serviceCategoryId: 2,
        name: "Experiencia Piel con Piel",
        slug: "piel-con-piel",
        shortDescription: "Cercanía y calidez en su forma más pura.",
        longDescription: null,
        durationMinutes: 60,
        price: 230000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Contacto directo", "Máxima cercanía"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 4,
        isActive: true,
      },
      {
        id: 8,
        serviceCategoryId: 2,
        name: "Cuerpo a Cuerpo",
        slug: "cuerpo-a-cuerpo",
        shortDescription: "Técnica clásica de deslizamiento corporal para una relajación absoluta.",
        longDescription: null,
        durationMinutes: 75,
        price: 260000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Deslizamiento corporal", "Relajación absoluta"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 5,
        isActive: true,
      },
    ],
  },
  {
    id: 3,
    name: "Masajes Sensoriales",
    slug: "sensoriales",
    description: "Sesiones de 60 minutos enfocadas en el placer de los sentidos, con tiempo adicional opcional.",
    highlight: null,
    displayOrder: 3,
    isActive: true,
    services: [
      {
        id: 9,
        serviceCategoryId: 3,
        name: "Masaje Sensorial",
        slug: "masaje-sensorial",
        shortDescription: "60 minutos de estimulación de los sentidos, con opción de vestidura sensorial.",
        longDescription: "Una sesión enfocada en despertar cada sentido, con la posibilidad de añadir tiempo extra y elegir la modalidad con vestidura sensorial (en panty).",
        durationMinutes: 60,
        price: 200000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Opción con vestidura sensorial (en panty)", "Tiempo adicional disponible"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: true,
        allowsExtraTime: true,
        isCoupleExperience: false,
        displayOrder: 1,
        isActive: true,
      },
    ],
  },
  {
    id: 4,
    name: "Experiencias en Pareja",
    slug: "experiencias-pareja",
    description: "Momentos diseñados para compartir, conectar y explorar en compañía.",
    highlight: null,
    displayOrder: 4,
    isActive: true,
    services: [
      {
        id: 10,
        serviceCategoryId: 4,
        name: "Experiencia en Pareja",
        slug: "experiencia-en-pareja",
        shortDescription: "Un masajista dedicado para cada persona, en la misma habitación.",
        longDescription: "Cada integrante de la pareja disfruta de su propio terapeuta, viviendo la experiencia al mismo tiempo y en el mismo espacio.",
        durationMinutes: 60,
        price: 480000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Un masajista por persona", "Misma habitación", "Sincronía total"],
        requiresTwoTherapists: true,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: true,
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 11,
        serviceCategoryId: 4,
        name: "Masaje Interactivo",
        slug: "masaje-interactivo",
        shortDescription: "El terapeuta guía a la pareja para que se masajeen mutuamente.",
        longDescription: null,
        durationMinutes: 60,
        price: 350000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Guiado por un terapeuta", "Conexión activa en pareja"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: true,
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 12,
        serviceCategoryId: 4,
        name: "Masaje Voyerista",
        slug: "masaje-voyerista",
        shortDescription: "El Arte de Mirar: conexión a través de los sentidos.",
        longDescription: "Uno de los dos se entrega por completo a la relajación mientras el otro observa, alimentando la fantasía y la complicidad de la pareja.",
        durationMinutes: 60,
        price: 260000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Uno se relaja, el otro observa", "Alimenta la complicidad"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: true,
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  {
    id: 5,
    name: "Relajación y Muscular",
    slug: "relajacion-muscular",
    description: "Terapias clásicas enfocadas en el bienestar físico y la recuperación muscular.",
    highlight: null,
    displayOrder: 5,
    isActive: true,
    services: [
      {
        id: 13,
        serviceCategoryId: 5,
        name: "Masaje de Relajación Clásico",
        slug: "relajacion-clasica",
        shortDescription: "Técnica sueca clásica para liberar el estrés del día a día.",
        longDescription: null,
        durationMinutes: 60,
        price: 150000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Técnica sueca", "Libera estrés"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 1,
        isActive: true,
      },
      {
        id: 14,
        serviceCategoryId: 5,
        name: "Exfoliación Corporal",
        slug: "exfoliacion-corporal",
        shortDescription: "Renueva tu piel con una exfoliación completa de cuerpo.",
        longDescription: null,
        durationMinutes: 45,
        price: 130000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Piel renovada", "Sales y aceites naturales"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 2,
        isActive: true,
      },
      {
        id: 15,
        serviceCategoryId: 5,
        name: "Masaje en Pies (Reflexología)",
        slug: "masaje-pies-reflexologia",
        shortDescription: "Puntos de reflexología para aliviar la fatiga y activar la circulación.",
        longDescription: null,
        durationMinutes: 30,
        price: 90000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Reflexología", "Activa la circulación"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 3,
        isActive: true,
      },
      {
        id: 16,
        serviceCategoryId: 5,
        name: "Recuperación Muscular Profunda",
        slug: "recuperacion-muscular-profunda",
        shortDescription: "Técnica de tejido profundo para deportistas y tensión crónica.",
        longDescription: null,
        durationMinutes: 75,
        price: 220000,
        imageUrl: null,
        imageGallery: [],
        highlights: ["Tejido profundo", "Ideal post-entrenamiento"],
        requiresTwoTherapists: false,
        hasSensoryDressOption: false,
        allowsExtraTime: false,
        isCoupleExperience: false,
        displayOrder: 4,
        isActive: true,
      },
    ],
  },
];

export const MOCK_MASSEUSES: Masseuse[] = [
  { id: 1, stageName: "Valentina", age: 28, bio: "Especialista en rituales tántricos y terapias de contacto total, con más de 5 años de experiencia.", photoUrl: null, photoGallery: [], displayOrder: 1, isActive: true },
  { id: 2, stageName: "Isabella", age: 25, bio: "Experta en masajes sensoriales y experiencias en pareja, enfocada en la conexión y la calidez.", photoUrl: null, photoGallery: [], displayOrder: 2, isActive: true },
  { id: 3, stageName: "Camila", age: 31, bio: "Terapeuta certificada en recuperación muscular y piedras volcánicas.", photoUrl: null, photoGallery: [], displayOrder: 3, isActive: true },
  { id: 4, stageName: "Sofía", age: 27, bio: "Especialista en masajes a cuatro manos y rituales L'AMOUR.", photoUrl: null, photoGallery: [], displayOrder: 4, isActive: true },
];
